import type { Tour } from 'nextstepjs';

export const steps: Tour[] = [
  {
    tour: 'welcomeTour',
    steps: [
      {
        icon: '',
        title: 'Welcome to Simprove!',
        content: "Want a quick tour to see what's available?",
        // selector: "#dashboard",    
        side: 'bottom',           
        showControls: true,
        showSkip: true,
        pointerPadding: 10,
        pointerRadius: 10,
      },
      {
        icon: '',
        title: 'Track your lifetime averages',
        content: "A snapshot of your lifetime performance - total shots, sessions, longest carry, and most used club. These update automatically as you log more data.",
        selector: '#stats-row',
        side: 'right',
        showControls: true,
        showSkip: true,
        pointerPadding: 10,
        pointerRadius: 10,
      },
      {
        icon: '',
        title: 'View your averages',
        content: 'Click on the different metrics up top to see how your averages over time for each club in your bag. Hover over each bar to see a more detailed breakdown.',
        selector: '#averages-graph',
        side: 'right',
        showControls: true,
        showSkip: true,
        pointerPadding: 10,
        pointerRadius: 10,
      },
      {
        icon: '',
        title: 'View your average swing metrics',
        content: "Click on a club to see your average club path, face angle, and attack angle.",
        selector: '#swing-metrics',
        side: 'right',
        showControls: true,
        showSkip: true,
        pointerPadding: 10,
        pointerRadius: 10,
      },
      {
        icon: '',
        title: 'View your average miss tendencies',
        content: "Click on a club to see where your shots are missing",
        selector: '#miss-tendency',
        side: 'right',
        showControls: true,
        showSkip: true,
        pointerPadding: 10,
        pointerRadius: 10,
      },
       {
        icon: '',
        title: 'See your recent activity',
        content: "Keep up-to-date with your latest activity - imported sessions, broken personal records, and unlocked badges.",
        selector: '#recent-activity',
        side: 'left',
        showControls: true,
        showSkip: true,
        pointerPadding: 10,
        pointerRadius: 10,
      },
       {
        icon: '',
        title: 'Stay productive with a lesson plan',
        content: "Create and follow a personalized lesson plan to improve your game.",
        selector: '#lesson-plan',
        side: 'left',
        showControls: true,
        showSkip: true,
        pointerPadding: 10,
        pointerRadius: 10,
      },
      {
        icon: '',
        title: 'Upload a session',
        content: "Upload your exported session data in .csv format from your launch monitor software.",
        selector: '#upload-btn',
        side: 'bottom',
        showControls: true,
        showSkip: true,
        pointerPadding: 10,
        pointerRadius: 10,
      }
    ],
  },
];