import type { Tour } from 'nextstepjs';

export const steps: Tour[] = [
  {
    tour: 'welcomeTour',
    steps: [
      {
        icon: '👋',
        title: 'Welcome!',
        content: "Lets get started",
        // selector: "#dashboard",    
        side: 'bottom',           
        showControls: true,
        showSkip: true,
        pointerPadding: 10,
        pointerRadius: 10,
      },
      {
        icon: '⚡',
        title: 'Fast and Accurate Tracking',
        content: "Simprove uses advanced computer vision to track your golf performance with precision.",
        selector: '#stats-row',
        side: 'right',
        showControls: true,
        showSkip: true,
        pointerPadding: 10,
        pointerRadius: 10,
      },
      {
        icon: '⚡',
        title: 'Fast and Accurate Tracking',
        content: "Simprove uses advanced computer vision to track your golf performance with precision.",
        selector: '#averages-graph',
        side: 'right',
        showControls: true,
        showSkip: true,
        pointerPadding: 10,
        pointerRadius: 10,
      },
      {
        icon: '⚡',
        title: 'Fast and Accurate Tracking',
        content: "Simprove uses advanced computer vision to track your golf performance with precision.",
        selector: '#swing-metrics',
        side: 'right',
        showControls: true,
        showSkip: true,
        pointerPadding: 10,
        pointerRadius: 10,
      },
      {
        icon: '⚡',
        title: 'Fast and Accurate Tracking',
        content: "Simprove uses advanced computer vision to track your golf performance with precision.",
        selector: '#miss-tendency',
        side: 'right',
        showControls: true,
        showSkip: true,
        pointerPadding: 10,
        pointerRadius: 10,
      },
       {
        icon: '⚡',
        title: 'Fast and Accurate Tracking',
        content: "Simprove uses advanced computer vision to track your golf performance with precision.",
        selector: '#recent-activity',
        side: 'left',
        showControls: true,
        showSkip: true,
        pointerPadding: 10,
        pointerRadius: 10,
      },
       {
        icon: '⚡',
        title: 'Fast and Accurate Tracking',
        content: "Simprove uses advanced computer vision to track your golf performance with precision.",
        selector: '#lesson-plan',
        side: 'left',
        showControls: true,
        showSkip: true,
        pointerPadding: 10,
        pointerRadius: 10,
      }
    ],
  },
];